### ISSUE TITLE
Confused by this idiom: tap(... {})

### ISSUE THREAD

**Issue by paulreimer** [kirkshoop/twitter#10]
For example here:
https://github.com/kirkshoop/twitter/blob/6654b267a12184847e3a5b7cbf2eddd230ac6e29/rxcurl.h#L158-L162

I'm guessing this adds a refcount to the `shared_ptr<http_state> requestState` when it is captured, so that its lifetime is at least as long as the observable's. And that it is captured in both the `chunks` and `complete` observables, since it is possible that the `complete` observable may have finished before the `chunks` observable (or vice versa). Is that correct?

If so, then another question: only one such `tap` is truly required, right? They both extend the lifetime of the captures in the `tap` to (at least) the lifetime of the observable that came _before_ it (which in this case is the same underlying observable for both `complete` and `chunks`), not the observables that come after it.

**Comment by kirkshoop** [comment]
you are correct. These extend the lifetime of `requestState`. Both are required because either one could be subscribed to and then `r` allowed to go out of scope. This destructs `body.chunks` and `body.complete`. if only one had the `tap` but the other one was the only one subscribed, then the lifetime would end.

**Comment by paulreimer** [comment]
Oh of course! I forgot about the case where you might only subscribe to one and not the other. Thanks that makes perfect sense.

**Comment by paulreimer** [comment]
On the topic of lifetimes, I'm guessing `string_view`s are in general dangerous for use as values within Observables unless everything is immediate/identity scheduled? But is the Observable pattern otherwise amenable to zero-copy techniques, or is there some safe subset? (I'm on an embedded platform, and my `curl_multi` API uses `delegate`s of `string_view`s, so it would be nice to keep that aspect).
