### ISSUE TITLE
No reducers makes only the first renderer work.

### ISSUE THREAD

**Issue by jc211** [kirkshoop/twitter#8]
I am building an application following the same pattern used by the twitter project. Whilst developing, I kept the reducer list empty, as I had not implemented them yet (I was working backwards, creating the views first).  The behavior I encountered was that when the reducer list was empty, only the first renderer added to the vector is actually rendered. Its almost as though, with_latest_from, doesn't work with the start_with coming from  the viewModels stream. (I commented out the filter on the viewmodels that checks for recency, and it still behaves the same way)

Anyway it took me quite a while to track the problem down, and I thought other people should be aware of this behavior.

My question is, is this behavior expected? Why is it that only the first renderer is working and the others aren't when the reducer list is empty?

**Comment by kirkshoop** [comment]
Thanks! you found a bug :)

The [fix](https://github.com/kirkshoop/twitter/commit/1c7058d54a43a532874222e0cfcc5ff2a89cc513) is simple. 

However, while looking at this I saw an opportunity to improve the pattern a little, so I may make a larger change to only use `with_latest_from` once.

**Comment by kirkshoop** [comment]
yep - the pattern [change](https://github.com/kirkshoop/twitter/commit/8314fcea02f403e20c25202a9fefbb2bb5c63448) worked!

**Comment by jc211** [comment]
Nice! I like the new pattern especially since you only assert the main thread once. 
With regards to the fix, you mention in your commit: 
"the problem is that the `start_with` is before the `publish` so its
value only arrives at the first renderer." 
Just curious as to the following: how is it that an on_next from a viewmodel stream is propagated to all renderers but a start_with is only propagated to the first subscriber?

**Comment by kirkshoop** [comment]
Thanks!

`start_with` produces the start value during the `subscribe` and then subscribes to the source for the rest of the values. `start_with` is similar to `just( ) | concat(source)`.

`publish() | ref_count()` will run the `start_with` during the first renderer call to `subscribe` and then the next renderer call to `subscribe` will not receive the `start_with` value, but will receive subsequent calls to `on_next`.

`replay(1) | ref_count()` will remember the most recent `on_next` and send it to each renderer's call to `subscribe`
